# Generated by Django 5.0 on 2024-01-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='car_pic',
            field=models.ImageField(default='default_car.jpg', upload_to='car_pics'),
        ),
    ]
