# Generated by Django 5.0 on 2024-01-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_post_car_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='car_pic',
        ),
        migrations.AddField(
            model_name='post',
            name='car_image',
            field=models.ImageField(default='default_car.jpg', upload_to='car_images'),
        ),
    ]
