# Generated by Django 5.0 on 2024-01-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_post_car_pic_post_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='default_image',
            field=models.ImageField(default='media/default_car.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images'),
        ),
    ]
