# Generated by Django 5.0 on 2024-01-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_post_default_image_alter_post_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='default_image',
        ),
    ]
