# Generated by Django 5.0 on 2024-01-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='car_image',
        ),
        migrations.AddField(
            model_name='post',
            name='car_images',
            field=models.FileField(blank=True, null=True, upload_to='car_images'),
        ),
    ]
