# Generated by Django 5.0 on 2024-01-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_remove_post_car_image_post_car_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='car_images',
            field=models.ImageField(blank=True, null=True, upload_to='car_images'),
        ),
    ]
